"""
HSRL Tavern Spell Card Definitions

Auto-registers all 71 pool spells from bg_pool_spells.json.
Each spell is a purchasable, castable card with a gold cost and tech level.

Spell effects are resolved via SPELL_SCRIPT_REGISTRY from scripts.py.
When a spell is cast, its script_class.on_play(source, game) is called.
"""

import json
import os

from hsrl.core.enums import CardType, GameTag, Race, Rarity
from hsrl.core.card_db import register_card
from hsrl.cards.spells.scripts import SPELL_SCRIPT_REGISTRY

# ── Load pool spell data ──────────────────────────────────────────────────

_data_dir = os.path.join(os.path.dirname(__file__), "..", "..", "..", "data")
_spells_path = os.path.join(_data_dir, "bg_pool_spells.json")

try:
    with open(_spells_path) as f:
        _pool_spells = json.load(f)
except (FileNotFoundError, json.JSONDecodeError):
    _pool_spells = []

_registered_count = 0

for spell_data in _pool_spells:
    card_id = spell_data["id"]
    name = spell_data.get("name", card_id)
    cost = spell_data.get("cost", 0)
    tech_level = spell_data.get("tech_level", 1)
    script_class = SPELL_SCRIPT_REGISTRY.get(card_id)

    register_card(
        card_id=card_id,
        name=name,
        text="",
        cardtype=CardType.SPELL,
        race=Race.INVALID,
        tech_level=tech_level,
        rarity=Rarity.COMMON,
        tags={
            GameTag.COST: cost,
            GameTag.TECH_LEVEL: tech_level,
        },
        script_class=script_class,
    )
    _registered_count += 1

# ── Standard example spells (for testing) ──────────────────────────────────

class _ExampleTavernSpellEffectScript:
    """Cast: Give a random friendly minion +1/+1."""

    @staticmethod
    def on_play(source, game):
        import random
        from hsrl.core.actions import Buff
        living = [m for m in source.controller.board if not m.dead]
        if living:
            return Buff(random.choice(living), atk=1, health=1)
        return None


register_card(
    card_id="EXAMPLE_TAVERN_SPELL_EFFECT",
    name="Example Tavern Spell Effect",
    text="Give a random friendly minion +1/+1.",
    cardtype=CardType.SPELL,
    race=Race.INVALID,
    tech_level=1,
    rarity=Rarity.COMMON,
    tags={
        GameTag.COST: 1,
        GameTag.TECH_LEVEL: 1,
    },
    script_class=_ExampleTavernSpellEffectScript,
)

# ── Token spells (generated by hero powers / minion effects) ───────────────

register_card(
    card_id="BANANA_SPELL",
    name="Banana",
    text="Give a minion +1/+1.",
    cardtype=CardType.SPELL,
    race=Race.INVALID,
    tech_level=1,
    rarity=0,
    tags={
        GameTag.COST: 0,
        GameTag.TECH_LEVEL: 1,
    },
)

register_card(
    card_id="EXAMPLE_TAVERN_SPELL",
    name="Example Tavern Spell",
    text="Cast a simple tavern spell for testing.",
    cardtype=CardType.SPELL,
    race=Race.INVALID,
    tech_level=1,
    rarity=Rarity.COMMON,
    tags={
        GameTag.COST: 2,
        GameTag.TECH_LEVEL: 1,
    },
)
